const OrderActionTypes = {
  ORDER_CREATE_REQUEST:'ORDER_CREATE_REQUEST',
  ORDER_CREATE_SUCCESS:'ORDER_CREATE_SUCCESS',
  ORDER_CREATE_FAILURE:'ORDER_CREATE_FAILURE',
  // ORDER_RESET:'ORDER_RESET',
  ORDER_DETAILS_REQUEST: 'ORDER_DETAILS_REQUEST',
  ORDER_DETAILS_SUCCESS: 'ORDER_DETAILS_SUCCESS',
  ORDER_DETAILS_FAILURE: 'ORDER_DETAILS_FAILURE',
  ALL_ORDERS_REQUEST: 'ALL_ORDERS_REQUEST',
  ALL_ORDERS_SUCCESS: 'ALL_ORDERS_SUCCESS',
  ALL_ORDERS_FAILURE: 'ALL_ORDERS_FAILURE',
  MY_ORDERS_REQUEST: 'MY_ORDERS_REQUEST',
  MY_ORDERS_SUCCESS: 'MY_ORDERS_SUCCESS',
  MY_ORDERS_FAILURE: 'MY_ORDERS_FAILURE',
  ORDER_DELIVERED_REQUEST: 'ORDER_DELIVERED_REQUEST',
  ORDER_DELIVERED_SUCCESS: 'ORDER_DELIVERED_SUCCESS',
  ORDER_DELIVERED_FAILURE: 'ORDER_DELIVERED_FAILURE',
}

export default OrderActionTypes;