# Generated by Django 3.2.6 on 2021-09-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210924_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='/jimmieshop/placeholder_hg0tpq.png', null=True, upload_to='jimmieshop/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/jimmieshop/placeholder_hg0tpq.png', null=True, upload_to='jimmieshop/'),
        ),
    ]
