# Generated by Django 3.2.6 on 2021-09-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/jimmieshop/placeholder_hg0tpq', null=True, upload_to='jimmieshop/'),
        ),
    ]
